projectPath: vlocity
queries:
  - AttributeCategory
  - CalculationProcedure
  - ContextAction
  - ContextDimension
  - ContextScope
  - EntityFilter
  - ObjectClass
  - ObjectContextRule
  - ObjectLayout
  - OfferMigrationPlan
  - Pricebook2
  - PriceList
  - PricingVariable
  - Product2
  - Promotion
  - Rule
  - TimePlan
  - TimePolicy
  - UIFacet
  - UISection
  - VlocityFunction
  - VlocityPicklist
  - DataRaptor
  - OmniScript
  - IntegrationProcedure
  - CalculationMatrix
  - CalculationProcedure
  - ContractType
  - CpqConfigurationSetup
  - DocumentClause
  - DocumentTemplate
  - InterfaceImplementation
  - PricingPlanls
  - VlocityAction